apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "secret"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
    - name: mysql
      imagePullPolicy: Always
      image: naveenkumar9707/mysql:k8
      envFrom:
        - configMapRef:
            name: mysql-config
      ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
