apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    tier: db
spec:
  containers:
    - name: mongo
      imagePullPolicy: Always
      image: naveenkumar9707/mongo:k8
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongo
    tier: db
  ports:
    - port: 80
      targetPort: 27017
