apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
    - name: web
      image: naveenkumar9707/web:k8
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
